export const QUESTIONS = [
  ['Q01', 'Tôi thấy thoải mái khi tự quyết định cách làm mà không cần chờ nhóm đồng ý.'],
  ['Q02', 'Khi chọn một hướng đi, tôi thường ưu tiên điều phù hợp với mục tiêu cá nhân của mình.'],
  ['Q03', 'Tôi thường cân nhắc tác động của lựa chọn lên gia đình hoặc nhóm trước khi quyết định.'],
  ['Q04', 'Tôi làm việc tốt hơn khi cảm thấy mình đang cùng thuộc về một nhóm.'],
  ['Q05', 'Tôi chủ động giữ liên lạc và phối hợp để mọi người cùng tiến bộ.'],
  ['Q06', 'Tôi thường muốn tự xử lý khó khăn trước khi nhờ người khác hỗ trợ.'],
  ['Q07', 'Ý kiến của những người quan trọng với tôi có ảnh hưởng rõ đến lựa chọn của tôi.'],
  ['Q08', 'Tôi muốn xây dựng sự thân thuộc với mọi người trước khi bắt đầu việc quan trọng.'],
  ['Q09', 'Khi có mục tiêu, tôi thích bắt tay vào việc trước rồi làm quen dần với mọi người.'],
  ['Q10', 'Tôi xem việc hoàn thành đúng cam kết là cách thuyết phục nhất để tạo niềm tin.'],
  ['Q11', 'Một mối quan hệ tốt thường giúp tôi làm việc hiệu quả hơn về lâu dài.'],
  ['Q12', 'Trong dự án mới, tôi thường muốn chốt nhiệm vụ và thời hạn ngay từ đầu.'],
  ['Q13', 'Tôi ưu tiên kết quả cụ thể hơn việc duy trì một cuộc trò chuyện dài.'],
  ['Q14', 'Tôi muốn hiểu cách mọi người suy nghĩ trước khi thống nhất cách làm việc.'],
  ['Q15', 'Tôi có thể linh hoạt thời gian để giữ gìn một mối quan hệ quan trọng.'],
  ['Q16', 'Tôi sẵn sàng thử một cách mới nếu bước thử đó giúp tôi học nhanh hơn.'],
  ['Q17', 'Tôi có thể bắt đầu dù chưa biết chắc mọi việc sẽ diễn ra thế nào.'],
  ['Q18', 'Tôi thường tìm hiểu khá kỹ trước khi cam kết với một lựa chọn lớn.'],
  ['Q19', 'Nếu có thể sửa trong quá trình làm, tôi không muốn chờ quá lâu để bắt đầu.'],
  ['Q20', 'Tôi xem một sai sót nhỏ là dữ liệu để điều chỉnh, không nhất thiết là thất bại.'],
  ['Q21', 'Tôi muốn biết rõ tiêu chuẩn và quy trình trước khi bắt tay vào việc.'],
  ['Q22', 'Tôi cảm thấy yên tâm hơn khi đã chuẩn bị các phương án cho tình huống bất ngờ.'],
  ['Q23', 'Tôi thấy thoải mái khi đặt câu hỏi hoặc phản biện với người có vị trí cao hơn.'],
  ['Q24', 'Tôi thường chờ người có trách nhiệm chính đưa ra định hướng trước.'],
  ['Q25', 'Trong nhóm, tôi nghĩ mọi người nên có cơ hội lên tiếng tương đối như nhau.'],
  ['Q26', 'Tôi chú ý đến vai trò và kinh nghiệm của từng người khi quyết định cách trao đổi.'],
  ['Q27', 'Tôi thấy rõ ràng hơn khi biết ai là người có quyền quyết định cuối cùng.'],
  ['Q28', 'Tôi điều chỉnh cách xưng hô hoặc hành vi tùy theo vai trò của người đối diện.'],
  ['Q29', 'Tôi thường gọi thẳng vấn đề với người phụ trách nếu tôi thấy có điểm chưa hợp lý.'],
  ['Q30', 'Tôi cho rằng trật tự trong nhóm giúp mọi người biết trách nhiệm của mình.'],
  ['Q31', 'Một chức danh không làm cho ý kiến của ai đó tự động đúng hơn.'],
  ['Q32', 'Tôi thường quan sát thứ bậc trước khi chọn cách trình bày một đề xuất.'],
  ['Q33', 'Tôi thích môi trường cho phép mọi người trao đổi khá bình đẳng.'],
  ['Q34', 'Khi có yêu cầu, tôi thường nói thẳng điều mình cần.'],
  ['Q35', 'Tôi thấy phản hồi rõ ràng, ngay lúc cần, giúp mình tiến bộ nhanh hơn.'],
  ['Q36', 'Tôi thường bắt đầu bằng việc giải thích bối cảnh trước khi đi vào ý chính.'],
  ['Q37', 'Tôi thấy thoải mái khi nói “không” nếu một đề nghị không phù hợp.'],
  ['Q38', 'Với vấn đề nhạy cảm, tôi thường chọn cách nói giảm và chọn thời điểm riêng tư.'],
  ['Q39', 'Tôi chú ý nhiều đến sắc thái và điều chưa được nói ra trong một cuộc trò chuyện.'],
  ['Q40', 'Tôi có thể thay đổi cách diễn đạt để giữ cho mối quan hệ không bị căng thẳng.']
].map(([id, text]) => ({id, text}));
